server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://fd:fd@localhost:8761/eureka/

spring:
  application:
    name: fd-modules-upms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  profiles:
#    active: dev
  cloud:
    config:
      name: application
      profile: dev
      label: master
      uri: http://localhost:8001/

