server:
  port: 8001

spring:
  application:
    name: fd-config
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/jack-fd/fd-cloud
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: config
          # git仓库的账号
          username:
          # git仓库的密码
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://fd:fd@localhost:8761/eureka/